name: Check for releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check for latest release
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh api repos/gwdevhub/GWToolboxpp/releases/latest --jq .tag_name)
          echo "Latest upstream release tag: $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

          git tag

          if git show-ref --tags --quiet --verify "refs/tags/$TAG"; then
            echo "Already processed."
            echo "run=false" >> "$GITHUB_OUTPUT"
          else
            echo "New version detected."
          fi

      - name: Install rust
        if: steps.check.outputs.run != 'false'
        uses: dtolnay/rust-toolchain@stable

      - name: Download & patch gwca.dll
        if: steps.check.outputs.run != 'false'
        run: |
          curl -OL https://raw.githubusercontent.com/gwdevhub/GWToolboxpp/${{ steps.check.outputs.tag }}/Dependencies/GWCA/bin/gwca.dll
          cargo run

      - name: Create tag
        if: steps.check.outputs.run != 'false'
        run: |
          git tag ${{ steps.check.outputs.tag }}
          git push origin ${{ steps.check.outputs.tag }}

      - name: Publish modified gwca.dll to github
        if: steps.check.outputs.run != 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.check.outputs.tag }}
          tag_name: ${{ steps.check.outputs.tag }}
          files: gwca.dll
